import { APIRequestContext, expect } from '@playwright/test'; // Importa el motor de peticiones y aserciones de Playwright
import { Booking, BookingResponse } from '../data/BookingInterfaces'; // Importa los contratos de datos para reservas y respuestas

/**
 * BookingClient class to handle all interactions with the /booking endpoint.
 * This follows the API Object Pattern to centralize HTTP request logic.
 */
export class BookingClient { // Define la clase para centralizar las operaciones sobre las reservas
  private request: APIRequestContext; // Declara la variable para el cliente de peticiones HTTP

  // Constructor receives the request context from Playwright
  constructor(request: APIRequestContext) { // Recibe el contexto necesario para hablar con la API
    this.request = request; // Almacena el contexto inyectado para realizar llamadas en toda la clase
  } // Finaliza la inicialización

  /**
   * Verifica la disponibilidad de la API (Health Check).
   * @returns El estado de la respuesta.
   */
  async checkHealth(): Promise<number> { // Método para validar que el servicio está operativo (Bonus Point)
    const response = await this.request.get('/ping'); // Realiza una petición GET al endpoint de salud
    expect(response.status(), 'API Health Check failed').toBe(201); // En esta API, ping devuelve 201
    return response.status(); // Devuelve el código de estado
  } // Finaliza el método de salud

  /**
   * Sends a POST request to create a new booking.
   * @param bookingData The dynamic data generated by the factory.
   * @returns A promise that resolves to the API response containing the ID.
   */
  async createBooking(bookingData: Booking): Promise<BookingResponse> { // Método para registrar una nueva reserva en el sistema
    const response = await this.request.post('/booking', { // Envía una petición POST al recurso de reservas
      data: bookingData, // Envía la información de la reserva en el cuerpo del mensaje
    }); // Espera a que el servidor procese la creación

    expect(response.ok()).toBeTruthy(); // Verifica que el servidor haya respondido con un código de éxito
    
    return await response.json(); // Convierte la respuesta del servidor en un objeto JSON y lo devuelve
  } // Finaliza el método de creación de reserva

  /**
   * Realiza una petición GET para obtener los detalles de una reserva específica.
   * @param id El identificador único de la reserva.
   * @returns Una promesa con los datos de la reserva encontrados.
   */
  async getBooking(id: number): Promise<Booking> { // Método para consultar una reserva por su identificador
    const response = await this.request.get(`/booking/${id}`); // Ejecuta la petición GET usando el ID en la URL

    expect(response.ok()).toBeTruthy(); // Valida que el servidor responda con éxito (Status 200 OK)
    
    return await response.json(); // Retorna el cuerpo de la respuesta parseado como un objeto Booking
  } // Finaliza el método de consulta de reserva

  /**
   * Realiza una actualización parcial de la reserva utilizando el método PATCH.
   * @param id El identificador único de la reserva a modificar.
   * @param partialData Objeto con los campos específicos que se desean actualizar.
   * @param token El token de seguridad obtenido previamente.
   * @returns Una promesa con los datos actualizados de la reserva.
   */
  async updatePartialBooking(id: number, partialData: Partial<Booking>, token: string): Promise<Booking> { // Método para actualizar campos específicos
    const response = await this.request.patch(`/booking/${id}`, { // Ejecuta la petición PATCH al endpoint de la reserva
      data: partialData, // Envía solo los datos que queremos cambiar
      headers: { // Define los encabezados de la petición
        'Cookie': `token=${token}`, // Incluye el token de seguridad en el formato de cookie requerido por la API
      }, // Cierra la definición de encabezados
    }); // Finaliza la ejecución del PATCH

    expect(response.ok()).toBeTruthy(); // Valida que la actualización haya sido aceptada por el servidor
    return await response.json(); // Retorna el objeto de la reserva con los cambios aplicados
  } // Finaliza el método de actualización parcial

  /**
   * Elimina una reserva del sistema utilizando el método DELETE.
   * @param id El identificador único de la reserva a eliminar.
   * @param token El token de seguridad para autorizar la eliminación.
   */
  async deleteBooking(id: number, token: string): Promise<void> { // Método para borrar un registro del servidor
    const response = await this.request.delete(`/booking/${id}`, { // Envía la petición DELETE a la ruta específica
      headers: { // Define los encabezados necesarios para la operación
        'Cookie': `token=${token}`, // Provee el token de autorización en la cookie
      }, // Cierra los encabezados
    }); // Finaliza la ejecución del borrado

    expect(response.status()).toBe(201); // Valida que el servidor responda con un código 201 (Created/Deleted en esta API)
  } // Finaliza el método de eliminación
} // Cierra la clase BookingClient
